const CACHE_NAME="openvox-0.9.1-beta.1-3039c3f3a86b";
const CACHE_PREFIX='openvox-';
const BASE="/OpenVox/";
const PRECACHE=["/OpenVox/404.html","/OpenVox/about/index.html","/OpenVox/academy/index.html","/OpenVox/analyze/index.html","/OpenVox/assets/framework-B4sbyuL8.js","/OpenVox/assets/index-7MqG8Wbr.js","/OpenVox/assets/index-Bz0LwPMQ.css","/OpenVox/assets/midi-engine-CUHAmaY6.js","/OpenVox/audio-lab/index.html","/OpenVox/choir/index.html","/OpenVox/icons/openvox-180.png","/OpenVox/icons/openvox-192.png","/OpenVox/icons/openvox-512.png","/OpenVox/index.html","/OpenVox/instruments/index.html","/OpenVox/manifest.webmanifest","/OpenVox/mixer/index.html","/OpenVox/openvox-icon.svg","/OpenVox/practice/index.html","/OpenVox/privacy/index.html","/OpenVox/pro-lab/dsp-library.js","/OpenVox/pro-lab/pro-audio-lab.js","/OpenVox/progress/index.html","/OpenVox/projects/index.html","/OpenVox/robots.txt","/OpenVox/score/index.html","/OpenVox/settings/index.html","/OpenVox/sitemap.xml","/OpenVox/studio/index.html","/OpenVox/track-lab/index.html","/OpenVox/transcribe/index.html","/OpenVox/wasm/openvox_dsp.wasm","/OpenVox/worklets/audio-processor.js"];
const INDEX=BASE+'index.html';
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(PRECACHE)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&key!==CACHE_NAME).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));});
async function networkFirst(request){const cache=await caches.open(CACHE_NAME);try{const response=await fetch(request);if(response&&response.ok)await cache.put(request,response.clone());return response;}catch(error){return (await cache.match(request))||(request.mode==='navigate'?await cache.match(INDEX):undefined)||Promise.reject(error);}}
async function cacheFirst(request){const cache=await caches.open(CACHE_NAME);const cached=await cache.match(request);if(cached)return cached;const response=await fetch(request);if(response&&response.ok)await cache.put(request,response.clone());return response;}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;const runtimeStable=url.pathname.includes('/wasm/')||url.pathname.includes('/worklets/')||url.pathname.includes('/pro-lab/');event.respondWith(request.mode==='navigate'||runtimeStable?networkFirst(request):cacheFirst(request));});
